#!/usr/bin/env python3
"""Build deterministic entry scaffolds from one root evidence packet."""

import argparse
import hashlib
import json
import re
import shutil
import tempfile
import unicodedata
import uuid
from collections import Counter, defaultdict
from pathlib import Path

try:
    from .build_entry_bundles import load_packet, packet_sha256, selector_matches
except ImportError:
    from build_entry_bundles import load_packet, packet_sha256, selector_matches


REVIEW = "[REVIEW REQUIRED]"
GENERATED_WARNING = (
    "<!-- Immutable generated input. Do not edit this file in place. Preserve "
    "packet-backed fields when copying it into an authored draft. -->"
)
GENERATED_MANIFEST = ".entry-scaffold-generated.json"
BUNDLE_MANIFEST = ".entry-bundle-generated.json"
ROOT_ID_RE = re.compile(r"^root_\d{6}$")
BRANCH_ID_RE = re.compile(r"^B\d{3}$")


def cell(value):
    return " ".join(str(value or "").split()).replace("|", "\\|")


def list_field(label, value):
    rendered = cell(value)
    return f"- {label}: {rendered}" if rendered else f"- {label}:"


def branch_ref(branch):
    return f"{branch['root_id']}/{branch['branch_id']}"


def branch_filename(branch):
    return f"{branch['root_id']}--{branch['branch_id']}.md"


def review(label):
    return f"[REVIEW REQUIRED: {label}]"


def split_ids(value):
    return [item.strip() for item in re.split(r"[;,]", value or "") if item.strip()]


def arabic_key(value, drop_article=False):
    text = unicodedata.normalize("NFKD", (value or "").replace("\u0670", "ا"))
    text = "".join(
        character
        for character in text
        if unicodedata.category(character) != "Mn"
        and not character.isspace()
        and character != "ـ"
    )
    if drop_article and text.startswith("ال"):
        text = text[2:]
    return text


def packet_envelope(packet):
    root_ids = [row.get("root_id", "") for row in packet.get("v4_roots", [])]
    if not root_ids or any(not ROOT_ID_RE.fullmatch(root_id) for root_id in root_ids):
        raise ValueError(f"Invalid V4 root IDs: {root_ids}")
    if len(root_ids) != len(set(root_ids)):
        raise ValueError(f"Duplicate V4 root IDs: {root_ids}")
    expected = "--".join(root_ids)
    actual = packet.get("root_envelope_id") or expected
    if actual != expected:
        raise ValueError(f"Envelope {actual!r} does not match ordered roots {expected!r}")
    return expected


def validate_packet(packet):
    if not isinstance(packet, dict):
        raise ValueError("Packet must be a JSON object")
    required_types = {
        "v4_roots": list,
        "branches": list,
        "dictionary_sources": list,
        "lexical_senses": list,
        "branch_lexical_links": list,
        "qac": dict,
        "attachments": dict,
        "qnet": dict,
    }
    for key, expected_type in required_types.items():
        if not isinstance(packet.get(key), expected_type):
            raise ValueError(f"Packet field {key!r} must be {expected_type.__name__}")
    envelope = packet_envelope(packet)
    root_ids = {row["root_id"] for row in packet["v4_roots"]}
    branch_keys = []
    for branch in packet.get("branches", []):
        root_id = branch.get("root_id", "")
        branch_id = branch.get("branch_id", "")
        if root_id not in root_ids or not BRANCH_ID_RE.fullmatch(branch_id):
            raise ValueError(f"Invalid branch identity: {root_id}/{branch_id}")
        branch_keys.append((root_id, branch_id))
    if len(branch_keys) != len(set(branch_keys)):
        raise ValueError("Duplicate branch identities in packet")

    sense_keys = [
        (row.get("root_id"), row.get("lexical_unit_id"))
        for row in packet.get("lexical_senses", [])
    ]
    if len(sense_keys) != len(set(sense_keys)):
        raise ValueError("Duplicate lexical sense identities in packet")
    branch_key_set = set(branch_keys)
    sense_key_set = set(sense_keys)
    link_keys = []
    for link in packet.get("branch_lexical_links", []):
        branch_key = (link.get("root_id"), link.get("branch_id"))
        sense_key = (link.get("root_id"), link.get("lexical_unit_id"))
        if branch_key not in branch_key_set or sense_key not in sense_key_set:
            raise ValueError(f"Dangling lexical link: {link}")
        link_keys.append(branch_key + (link.get("lexical_unit_id"),))
    if len(link_keys) != len(set(link_keys)):
        raise ValueError("Duplicate branch lexical links in packet")

    qac_refs = [row.get("qac_ref") for row in packet.get("qac", {}).get("occurrences", [])]
    if len(qac_refs) != len(set(qac_refs)):
        raise ValueError("Duplicate QAC occurrence references in packet")
    return envelope


def file_sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def preflight_branch_bundles(project, packet, packet_path):
    envelope = packet_envelope(packet)
    bundle_dir = project / "data/output/entry_bundles" / envelope
    manifest_path = bundle_dir / BUNDLE_MANIFEST
    if not manifest_path.is_file():
        raise ValueError(
            f"Missing generated bundle manifest: {manifest_path}. "
            f"Run scripts/build_entry_bundles.py {envelope!r}."
        )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    expected_roster = [branch_ref(branch) for branch in packet["branches"]]
    if (
        manifest.get("format") != 1
        or manifest.get("root_envelope_id") != envelope
        or manifest.get("packet_sha256") != packet_sha256(packet)
        or manifest.get("branches") != expected_roster
    ):
        raise ValueError(f"Stale or mismatched generated bundle manifest: {manifest_path}")
    files = manifest.get("files")
    if not isinstance(files, dict):
        raise ValueError(f"Bundle manifest lacks generated file hashes: {manifest_path}")
    expected_files = {"ROOT.md", "INDEX.md"} | {
        f"branches/{branch_filename(branch)}" for branch in packet["branches"]
    }
    if set(files) != expected_files:
        raise ValueError(f"Bundle manifest file roster differs from packet: {manifest_path}")
    for relative, digest in files.items():
        path = bundle_dir / relative
        if not path.is_file() or file_sha256(path) != digest:
            raise ValueError(f"Missing or changed generated branch-bundle file: {path}")
    return bundle_dir


def occurrence_unit_id(occurrence):
    return f"q:{occurrence['surah']}:{occurrence['ayah']}:{occurrence['word_index']}"


def attachment_links(packet):
    """Map QAC words to attachment instances without guessing token alignment."""
    instances = (
        packet["attachments"].get("verb_instances", [])
        + packet["attachments"].get("noun_instances", [])
    )
    by_unit = defaultdict(list)
    by_ayah = defaultdict(list)
    for instance in instances:
        unit_id = instance.get("word_unit_id") or instance.get("unit_id", "")
        if unit_id.startswith("q:"):
            by_unit[unit_id].append(instance)
        key = (str(instance.get("sura", "")), str(instance.get("ayah", "")))
        by_ayah[key].append(instance)

    occurrence_words = defaultdict(set)
    for row in packet["qac"]["occurrences"]:
        occurrence_words[(str(row["surah"]), str(row["ayah"]))].add(
            occurrence_unit_id(row)
        )

    result = {}
    for ayah_key, qac_units in occurrence_words.items():
        candidates = by_ayah.get(ayah_key, [])
        for qac_unit in qac_units:
            exact = by_unit.get(qac_unit, [])
            occurrence = next(
                row
                for row in packet["qac"]["occurrences"]
                if occurrence_unit_id(row) == qac_unit
            )
            root_key = arabic_key(occurrence.get("root_ar"))
            exact = [
                instance
                for instance in exact
                if arabic_key(instance.get("root_norm")) == root_key
            ]
            if exact:
                result[qac_unit] = {"method": "exact_word_unit", "instances": exact}
            elif len(qac_units) == 1 and len(candidates) == 1:
                candidate = candidates[0]
                qac_forms = {
                    arabic_key(occurrence.get("surface_ar"), drop_article=True),
                    arabic_key(occurrence.get("stem_ar"), drop_article=True),
                }
                attachment_forms = {
                    arabic_key(candidate.get("surface"), drop_article=True),
                    arabic_key(candidate.get("stem"), drop_article=True),
                }
                root_matches = arabic_key(candidate.get("root_norm")) == root_key
                form_matches = bool((qac_forms - {""}) & (attachment_forms - {""}))
                if root_matches and form_matches:
                    result[qac_unit] = {
                        "method": "unique_root_form_in_ayah",
                        "instances": candidates,
                    }
                else:
                    result[qac_unit] = {
                        "method": "unresolved",
                        "reason": "unique ayah candidate lacks corroborating root/form match",
                        "instances": candidates,
                    }
            else:
                result[qac_unit] = {
                    "method": "unresolved",
                    "reason": "attachment token alignment is not unique",
                    "instances": candidates,
                }
    return result


def attachment_rows_by_id(packet):
    return {
        row.get("unit_id", ""): row
        for row in packet["attachments"].get("attachments", [])
        if row.get("unit_id")
    }


def instance_attachment_ids(instance):
    fields = (
        "dependent_attachment_ids",
        "head_attachment_ids",
        "modifier_attachment_ids",
        "prep_attachment_ids",
        "object_attachment_ids",
        "subject_attachment_id",
        "clausal_attachment_ids",
    )
    ids = []
    for field in fields:
        ids.extend(split_ids(instance.get(field, "")))
    return list(dict.fromkeys(ids))


def render_frame(link, attachments_by_id):
    if not link or link["method"] == "unresolved":
        candidates = ", ".join(
            instance.get("word_unit_id") or instance.get("unit_id", "")
            for instance in (link or {}).get("instances", [])
        )
        reason = (link or {}).get("reason", "no attachment candidate")
        suffix = f"; candidates={candidates}" if candidates else ""
        return f"join=unresolved; reason={reason}{suffix}"

    parts = [f"join={link['method']}"]
    for instance in link["instances"]:
        unit_id = instance.get("word_unit_id") or instance.get("unit_id", "")
        if unit_id:
            parts.append(f"instance={unit_id}")
        for attachment_id in instance_attachment_ids(instance):
            row = attachments_by_id.get(attachment_id)
            if row:
                details = [
                    f"relation={row.get('relation', '')}",
                    f"status={row.get('status', '')}",
                    f"confidence={row.get('confidence', '')}",
                    f"evidence={row.get('evidence', '')}",
                    f"reason={row.get('reason', '')}",
                    f"dep={row.get('dep_unit_id', '')}:{row.get('dep_surface', '')}",
                    f"head={row.get('head_unit_id', '')}:{row.get('head_surface', '')}",
                ]
                for key in (
                    "obj_type",
                    "prep_base",
                    "prep_unit_id",
                    "choice_relation",
                ):
                    if row.get(key):
                        details.append(f"{key}={row[key]}")
                parts.append(
                    f"{attachment_id} [" + "; ".join(details) + "]"
                )
            else:
                parts.append(attachment_id)
    return "; ".join(dict.fromkeys(parts))


def linked_senses(packet):
    senses = {
        (row["root_id"], row["lexical_unit_id"]): row
        for row in packet["lexical_senses"]
    }
    result = defaultdict(list)
    for link in packet["branch_lexical_links"]:
        key = (link["root_id"], link["branch_id"])
        sense = senses.get((link["root_id"], link["lexical_unit_id"]))
        if sense:
            result[key].append(sense)
    return result


def render_root_header(packet, packet_path):
    roots = "; ".join(
        f"{row['root_id']} ({row['source_root_norm']})" for row in packet["v4_roots"]
    )
    summary = packet["qac"]["summary"]
    lines = [
        GENERATED_WARNING,
        "<!-- dictionary-entry-schema: 1 -->",
        f"# {packet['root_norm']}",
        "",
        f"- English transliteration: {review('root transliteration')}",
        f"- Türkçe çevriyazı: {review('kök çevriyazısı')}",
        "",
        "## Root identity",
        "",
        f"- Root envelope ID: `{packet['root_envelope_id']}`",
        f"- Normalized root: `{packet['root_join_key']}`",
        f"- Arabic root: `{packet['root_norm']}`",
        f"- English transliteration: {review('root transliteration')}",
        f"- Türkçe çevriyazı: {review('kök çevriyazısı')}",
        f"- V4 root records: {roots}",
        f"- Frozen branch records: {len(packet['branches'])}",
        f"- QAC rooted morphemes: {summary['morpheme_count']}",
        f"- Source snapshot: `{packet_path}`",
        "",
        "## Branch index",
        "",
        "| V4 branch | Arabic branch image | English transliteration | "
        "Türkçe çevriyazı | Cross-reference note |",
        "|---|---|---|---|---|",
    ]
    for branch in packet["branches"]:
        lines.append(
            f"| {branch_ref(branch)} | {cell(branch['branch_image_ar'])} | "
            f"{review('English transliteration')} | {review('Türkçe çevriyazı')} | "
            f"{review('cross-reference note or none')} |"
        )
    return "\n".join(lines).rstrip() + "\n"


def render_source_skeleton(source, passage_number):
    heading = source.get("source_id") or "unknown-source"
    headword = source.get("headword") or "-"
    return [
        f"#### {heading} — {headword} — passage {passage_number}",
        "",
        f"- Route status (generated): `{cell(source.get('route_status'))}`",
        f"- Route note (generated): {cell(source.get('route_note'))}",
        f"- Reference (generated): `{cell(source.get('source_ref'))}`",
        f"- Relationship: {review('editorial relationship classification')}",
        f"- Contribution: {review('source-grounded contribution')}",
        "",
        f"> {review('exact relevant Arabic excerpt from the supplied source text')}",
        "",
        f"English transliteration: {review('complete quotation transliteration')}",
        "",
        f"Türkçe çevriyazı: {review('alıntının eksiksiz çevriyazısı')}",
        "",
        f"English explanation: {review('source-grounded explanation')}",
        "",
        f"Türkçe açıklama: {review('kaynağa dayalı açıklama')}",
        "",
        f"Examples or special analysis: {review('examples, analysis, or none')}",
        "",
    ]


def branch_source_rows(packet, branch):
    handles = {item for item in (branch.get("source_refs") or "").split(";") if item}
    rows = [
        source
        for source in packet["dictionary_sources"]
        if source["root_id"] == branch["root_id"]
        and source.get("source_ref") in handles
        and source.get("route_status") != "no_match"
    ]
    matched = {source.get("source_ref") for source in rows}
    unmatched = sorted(handles - matched)
    gaps = [
        source
        for source in packet["dictionary_sources"]
        if source["root_id"] == branch["root_id"]
        and source.get("route_status") == "no_match"
    ]
    return rows, unmatched, gaps


def render_branch(packet, branch, senses, branch_bundle):
    ref = branch_ref(branch)
    sources, unmatched_handles, routing_gaps = branch_source_rows(packet, branch)
    lines = [
        GENERATED_WARNING,
        f"<!-- BEGIN BRANCH {ref} -->",
        f"## Branch {ref} — {branch['branch_image_ar']}",
        "",
        "### V4 identity",
        "",
        f"- Root record: `{branch['root_id']}`",
        f"- Branch record: `{branch['branch_id']}`",
        f"- Arabic image: {branch['branch_image_ar']}",
        f"- English transliteration: {review('branch-image transliteration')}",
        f"- Türkçe çevriyazı: {review('dal imgesi çevriyazısı')}",
        f"- English scaffold: {cell(branch.get('branch_image_en'))}",
        f"- English scaffold fit: `{cell(branch.get('image_en_fit'))}`",
        list_field("English scaffold gap note", branch.get("image_en_gap_note")),
        f"- V4 source references: {cell(branch.get('source_refs'))}",
        f"- V4 source phrase: {cell(branch.get('source_phrase_ar'))}",
        f"- V4 review note: {cell(branch.get('review_note'))}",
        f"- Required evidence bundle: `{branch_bundle}`",
        "- QNet discovery: use only the required evidence bundle's QNet appendix; it is not evidence.",
        "- V4 provenance: "
        f"`origin_corpus={cell(branch.get('origin_corpus'))}; "
        f"status={cell(branch.get('status'))}; "
        f"contaminated={cell(branch.get('contaminated'))}`",
        "",
        "### Concept and boundary",
        "",
        "#### English",
        "",
        review("complete English concept account from Arabic evidence"),
        "",
        "#### Türkçe",
        "",
        review("Arapça delilden bağımsız Türkçe kavram açıklaması"),
        "",
        "#### What belongs to the branch",
        "",
        f"- V4 Arabic boundary: {cell(branch.get('what_is_ar'))}",
        f"- {review('reader-facing English and Turkish explanation')}",
        "",
        "#### What does not belong to the branch",
        "",
        f"- V4 Arabic exclusion: {cell(branch.get('what_is_not_ar'))}",
        f"- {review('reader-facing English and Turkish explanation')}",
        "",
        "### Arabic contrasts",
        "",
        "| Arabic neighbor | English transliteration | Türkçe çevriyazı | "
        "Shared zone | Distinguishing axis | Evidence |",
        "|---|---|---|---|---|---|",
        f"| {review('verified neighbor or none')} | {REVIEW} | {REVIEW} | "
        f"{REVIEW} | {REVIEW} | {REVIEW} |",
        "",
        "### Lexical units and examples",
        "",
        "| Arabic expression | English transliteration | Türkçe çevriyazı | "
        "Kind/form | Meaning in this branch | Source/example |",
        "|---|---|---|---|---|---|",
    ]
    if senses:
        for sense in senses:
            meaning = (
                f"V4 Arabic: {sense.get('sense_ar', '')}; "
                f"English scaffold: {sense.get('sense_en', '')}"
            )
            source = (
                f"{sense.get('source_refs', '')}; "
                f"phrase: {sense.get('source_phrase_ar', '')}"
            )
            lines.append(
                f"| {cell(sense.get('expression_ar'))} | "
                f"{review('English transliteration')} | "
                f"{review('Türkçe çevriyazı')} | "
                f"{cell(sense.get('unit_kind'))} | {cell(meaning)} | {cell(source)} |"
            )
    else:
        lines.append("")

    lines += ["", "### Source audit", ""]
    for number, source in enumerate(sources, start=1):
        lines += render_source_skeleton(source, number)
    if unmatched_handles:
        lines += [
            "#### Unmatched V4 source handles",
            "",
            "> Packet routing did not supply an exact source row for these V4 handles. "
            "This is an evidence-routing gap, not source silence.",
            "",
        ]
        lines += [f"- `{cell(handle)}`" for handle in unmatched_handles]
        lines.append("")
    if routing_gaps:
        lines += [
            "#### Packet routing gaps",
            "",
            "> `no_match` is lookup metadata. It does not establish no located attestation, "
            "silence, or disagreement.",
            "",
            "| Source | Route status | Route note |",
            "|---|---|---|",
        ]
        for source in routing_gaps:
            lines.append(
                f"| {cell(source.get('source_id'))} | {cell(source.get('route_status'))} | "
                f"{cell(source.get('route_note'))} |"
            )
        lines.append("")

    lines += [
        "### English renderings and confusions",
        "",
        "| Rendering | Role | Preserves | Loses | Adds | Fit error | "
        "Collision or misleading concept |",
        "|---|---|---|---|---|---|---|",
        f"| {REVIEW} | {REVIEW} | {REVIEW} | {REVIEW} | {REVIEW} | {REVIEW} | {REVIEW} |",
        "",
        "### Turkish renderings and confusions",
        "",
        "| Karşılık | Rol | Koruduğu | Eksilttiği | Eklediği | Uyum hatası | "
        "Karıştırdığı kavram veya yanıltıcı sonuç |",
        "|---|---|---|---|---|---|---|",
        f"| {REVIEW} | {REVIEW} | {REVIEW} | {REVIEW} | {REVIEW} | {REVIEW} | {REVIEW} |",
        "",
        "### Target-language distinction notes",
        "",
        "#### English",
        "",
        review("English collision analysis or a brief evidence-based none statement"),
        "",
        "#### Türkçe",
        "",
        review("Türkçe çakışma incelemesi veya kısa ve kanıtlı yokluk açıklaması"),
        "",
        f"<!-- END BRANCH {ref} -->",
    ]
    return "\n".join(lines).rstrip() + "\n"


def forms_rows(packet, links, attachments_by_id):
    grouped = defaultdict(list)
    for row in packet["qac"]["occurrences"]:
        key = (
            row.get("lemma_ar", ""),
            row.get("surface_ar", ""),
            row.get("pos", ""),
            row.get("morph_features", ""),
        )
        grouped[key].append(row)

    rows = []
    for key, occurrences in sorted(
        grouped.items(), key=lambda item: (
            item[1][0]["surah"], item[1][0]["ayah"], item[1][0]["word_index"]
        )
    ):
        lemma, surface, pos, morphology = key
        joins = Counter()
        relations = Counter()
        statuses = Counter()
        for occurrence in occurrences:
            link = links.get(occurrence_unit_id(occurrence))
            joins[(link or {}).get("method", "unresolved")] += 1
            if link and link["method"] != "unresolved":
                for instance in link["instances"]:
                    for attachment_id in instance_attachment_ids(instance):
                        attachment = attachments_by_id.get(attachment_id, {})
                        if attachment.get("relation"):
                            relations[attachment["relation"]] += 1
                        if attachment.get("status"):
                            statuses[attachment["status"]] += 1
        parts = [
            "joins=" + ",".join(f"{name}:{count}" for name, count in sorted(joins.items()))
        ]
        if relations:
            parts.append(
                "relations="
                + ",".join(
                    f"{name}:{count}" for name, count in sorted(relations.items())
                )
            )
        if statuses:
            parts.append(
                "statuses="
                + ",".join(f"{name}:{count}" for name, count in sorted(statuses.items()))
            )
        observed = "; ".join(parts)
        rows.append((lemma, surface, pos, morphology, len(occurrences), observed))
    return rows


def render_aggregate_table(title, rows, columns):
    lines = [f"#### {title}", ""]
    if not rows:
        return lines + ["- No packet rows.", ""]
    lines += [
        "| " + " | ".join(columns) + " |",
        "|" + "---|" * len(columns),
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(row.get(column, "")) for column in columns) + " |")
    lines.append("")
    return lines


def aggregate_columns(rows):
    columns = []
    for row in rows:
        for key in row:
            if key not in columns:
                columns.append(key)
    return columns


def render_quran_observatory(packet):
    summary = packet["qac"]["summary"]
    links = attachment_links(packet)
    attachments_by_id = attachment_rows_by_id(packet)
    lines = [
        GENERATED_WARNING,
        "## Quran occurrence observatory",
        "",
        "> These are root-level observations. No occurrence is assigned to a V4 branch.",
        "",
        "### Census",
        "",
        f"- Rooted morphemes: {summary['morpheme_count']}",
        f"- Words: {summary['word_count']}",
        f"- Ayahs: {summary['ayah_count']}",
        f"- Surahs: {summary['surah_count']}",
        "",
        "### Forms and lemmas",
        "",
        "| Arabic lemma/form | English transliteration | Türkçe çevriyazı | "
        "POS/morphology | Count | Observed constructions |",
        "|---|---|---|---|---|---|",
    ]
    for lemma, surface, pos, morphology, count, constructions in forms_rows(
        packet, links, attachments_by_id
    ):
        arabic = f"lemma={lemma}; surface={surface}"
        lines.append(
            f"| {cell(arabic)} | {review('English transliteration')} | "
            f"{review('Türkçe çevriyazı')} | {cell(pos)}; {cell(morphology)} | "
            f"{count} | {cell(constructions)} |"
        )

    attachments = packet["attachments"]
    lines += [
        "",
        "### Attachment and construction observations",
        "",
        f"- Verb instances: {len(attachments.get('verb_instances', []))}",
        f"- Noun instances: {len(attachments.get('noun_instances', []))}",
        f"- Attachment rows: {len(attachments.get('attachments', []))}",
        f"- Aggregate verb frames: {len(attachments.get('verb_valency_frames', []))}",
        f"- Aggregate noun patterns: {len(attachments.get('noun_governing_patterns', []))}",
        "- Join labels below are mechanical provenance. "
        "`unique_root_form_in_ayah` requires one root occurrence, one attachment "
        "candidate, and corroborating normalized root and form; it is not a "
        "word-position match.",
        "",
    ]
    verb_frames = attachments.get("verb_valency_frames", [])
    noun_patterns = attachments.get("noun_governing_patterns", [])
    lines += render_aggregate_table(
        "Aggregate verb frames (packet fields)",
        verb_frames,
        aggregate_columns(verb_frames),
    )
    lines += render_aggregate_table(
        "Aggregate noun patterns (packet fields)",
        noun_patterns,
        aggregate_columns(noun_patterns),
    )
    lines += [
        "### Complete occurrences",
        "",
        "| QAC ref | Arabic surface | English transliteration | Türkçe çevriyazı | "
        "Lemma/form | Morphology | Observable frame/attachments | Ayah context handle |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in packet["qac"]["occurrences"]:
        handle = f"{row['surah']}:{row['ayah']}"
        lemma_form = f"{row.get('lemma_ar', '')}; measure={row.get('measure') or '—'}"
        frame = render_frame(links.get(occurrence_unit_id(row)), attachments_by_id)
        lines.append(
            f"| {row['qac_ref']} | {cell(row.get('surface_ar'))} | "
            f"{review('English transliteration')} | {review('Türkçe çevriyazı')} | "
            f"{cell(lemma_form)} | {cell(row.get('morph_features'))} | "
            f"{cell(frame)} | {handle} |"
        )

    lines += ["", "### Full ayah contexts", ""]
    for ayah in packet["qac"].get("ayah_contexts", []):
        lines += [
            f"#### {ayah['ref']}",
            "",
            ayah["surface_ar"],
            "",
            f"English transliteration: {review('complete ayah transliteration')}",
            "",
            f"Türkçe çevriyazı: {review('âyetin eksiksiz çevriyazısı')}",
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_bibliography_candidates(packet, packet_path):
    lines = [
        GENERATED_WARNING,
        "## Bibliography and evidence handles",
        "",
        "> Candidate handles only. The editor must retain only sources actually used.",
        "",
        "### Classical dictionaries",
        "",
    ]
    seen = set()
    for source in packet["dictionary_sources"]:
        key = (source.get("source_id"), source.get("source_ref"))
        if key in seen:
            continue
        seen.add(key)
        lines.append(
            f"- {cell(source.get('source_id'))}: `{cell(source.get('source_ref'))}` "
            f"(route_status={cell(source.get('route_status'))})"
        )
    lines += [
        "",
        "### Quran morphology and attachment evidence",
        "",
        f"- QAC packet: `{packet_path}`",
        "- Attachment packet: `data/upstream/attachments/final_v3/`",
        "",
        "### Target-language usage sources",
        "",
        f"- {review('list only English and Turkish sources actually used')}",
    ]
    return "\n".join(lines).rstrip() + "\n"


def render_scaffold_tree(packet, packet_path, output_dir, project):
    output_dir.mkdir(parents=True, exist_ok=True)
    branch_dir = output_dir / "branches"
    branch_dir.mkdir(parents=True, exist_ok=True)
    senses = linked_senses(packet)

    root_text = render_root_header(packet, packet_path)
    quran_text = render_quran_observatory(packet)
    bibliography_text = render_bibliography_candidates(packet, packet_path)
    (output_dir / "ROOT-HEADER.md").write_text(root_text, encoding="utf-8")
    (output_dir / "QURAN-OBSERVATORY.md").write_text(quran_text, encoding="utf-8")
    (output_dir / "BIBLIOGRAPHY-CANDIDATES.md").write_text(
        bibliography_text, encoding="utf-8"
    )

    index = [
        f"# Entry scaffolds: {packet['root_norm']}",
        "",
        "- [Root header and branch index](ROOT-HEADER.md)",
        "- [Quran observatory](QURAN-OBSERVATORY.md)",
        "- [Bibliography candidates](BIBLIOGRAPHY-CANDIDATES.md)",
        "- [Assembled generated scaffold](ASSEMBLED-SCAFFOLD.md)",
    ]
    branch_texts = []
    for branch in packet["branches"]:
        filename = branch_filename(branch)
        key = (branch["root_id"], branch["branch_id"])
        bundle = (
            project
            / "data/output/entry_bundles"
            / packet["root_envelope_id"]
            / "branches"
            / filename
        )
        try:
            bundle_label = bundle.relative_to(project)
        except ValueError:
            bundle_label = bundle
        branch_text = render_branch(packet, branch, senses[key], bundle_label)
        branch_texts.append(branch_text)
        (branch_dir / filename).write_text(branch_text, encoding="utf-8")
        index.append(f"- [{branch_ref(branch)}](branches/{filename})")
    (output_dir / "INDEX.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    assembled = "\n".join(
        [root_text, *branch_texts, quran_text, bibliography_text]
    )
    (output_dir / "ASSEMBLED-SCAFFOLD.md").write_text(assembled, encoding="utf-8")
    manifest = {
        "format": 1,
        "root_envelope_id": packet["root_envelope_id"],
        "packet": str(packet_path),
        "branches": [branch_ref(branch) for branch in packet["branches"]],
    }
    (output_dir / GENERATED_MANIFEST).write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def scaffold_destination(project, envelope, requested=None):
    project = project.resolve()
    components = [project / "data", project / "data/output", project / "data/output/entry_scaffolds"]
    for component in components:
        if component.is_symlink():
            raise ValueError(f"Generated scaffold namespace may not contain symlinks: {component}")
    output_root = (project / "data/output").resolve()
    root = project / "data/output/entry_scaffolds"
    resolved_root = root.resolve()
    try:
        relative = resolved_root.relative_to(output_root)
    except ValueError as error:
        raise ValueError(f"Scaffold root escapes data/output: {resolved_root}") from error
    if relative != Path("entry_scaffolds"):
        raise ValueError(f"Scaffold root redirects outside its namespace: {resolved_root}")
    expected = root / envelope
    requested_path = requested or expected
    if requested_path.is_symlink():
        raise ValueError(f"Scaffold destination may not be a symlink: {requested_path}")
    destination = requested_path.resolve()
    if destination != expected.resolve():
        raise ValueError(
            f"Scaffolds for {envelope} must be written to {expected}; got {destination}"
        )
    return resolved_root, destination


def verify_generated_tree(path, envelope):
    manifest_path = path / GENERATED_MANIFEST
    if not manifest_path.is_file():
        raise ValueError(f"Refusing to replace unmarked directory: {path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("format") != 1 or manifest.get("root_envelope_id") != envelope:
        raise ValueError(f"Generated-tree marker does not match {envelope}: {path}")


def validate_rendered_tree(path, packet):
    required = {
        "INDEX.md",
        "ROOT-HEADER.md",
        "QURAN-OBSERVATORY.md",
        "BIBLIOGRAPHY-CANDIDATES.md",
        "ASSEMBLED-SCAFFOLD.md",
        GENERATED_MANIFEST,
    }
    actual = {item.name for item in path.iterdir() if item.is_file()}
    missing = sorted(required - actual)
    if missing:
        raise ValueError(f"Staged scaffold tree is missing files: {missing}")
    branch_files = sorted(item.name for item in (path / "branches").glob("*.md"))
    expected = sorted(branch_filename(branch) for branch in packet["branches"])
    if branch_files != expected:
        raise ValueError(
            f"Staged branch scaffold set differs from packet: {branch_files} != {expected}"
        )


def recover_interrupted_replacement(scaffold_root, output_dir, envelope):
    backups = sorted(scaffold_root.glob(f".{envelope}.backup-*"))
    if not output_dir.exists() and len(backups) == 1:
        verify_generated_tree(backups[0], envelope)
        backups[0].rename(output_dir)
        backups = []
    if not output_dir.exists() and len(backups) > 1:
        raise ValueError(f"Multiple interrupted scaffold backups require inspection: {backups}")
    if output_dir.exists() and backups:
        verify_generated_tree(output_dir, envelope)
        for backup in backups:
            verify_generated_tree(backup, envelope)
            shutil.rmtree(backup)


def write_scaffolds(packet, packet_path, output_dir, project, force=False):
    envelope = validate_packet(packet)
    packet["root_envelope_id"] = envelope
    scaffold_root, output_dir = scaffold_destination(project, envelope, output_dir)
    scaffold_root.mkdir(parents=True, exist_ok=True)
    recover_interrupted_replacement(scaffold_root, output_dir, envelope)
    preflight_branch_bundles(project, packet, packet_path)

    if output_dir.exists() and any(output_dir.iterdir()):
        if not force:
            raise ValueError(
                f"Refusing to overwrite nonempty generated tree without --force: {output_dir}"
            )
        verify_generated_tree(output_dir, envelope)

    staging = Path(
        tempfile.mkdtemp(prefix=f".{envelope}.staging-", dir=str(scaffold_root))
    )
    backup = None
    try:
        render_scaffold_tree(packet, packet_path, staging, project)
        validate_rendered_tree(staging, packet)
        if output_dir.exists():
            if any(output_dir.iterdir()):
                backup = scaffold_root / f".{envelope}.backup-{uuid.uuid4().hex}"
                output_dir.rename(backup)
            else:
                output_dir.rmdir()
        staging.rename(output_dir)
        if backup:
            try:
                shutil.rmtree(backup)
            except OSError:
                pass
    except Exception:
        if staging.exists():
            shutil.rmtree(staging)
        if backup and backup.exists() and not output_dir.exists():
            backup.rename(output_dir)
        raise
    return output_dir


def main():
    project = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", help="V4 root_id, root envelope ID, or Arabic root selector")
    parser.add_argument("--packet", type=Path)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace a marker-verified generated scaffold tree using staged recovery",
    )
    args = parser.parse_args()

    packet_path, packet = load_packet(project, args.root, args.packet)
    envelope = validate_packet(packet)
    if args.packet and not selector_matches(packet, args.root):
        raise SystemExit(
            f"Root selector {args.root!r} does not match explicit packet {packet_path}"
        )
    packet["root_envelope_id"] = envelope
    _, output_dir = scaffold_destination(project, envelope, args.output_dir)
    output_dir = write_scaffolds(
        packet, packet_path, output_dir, project, force=args.force
    )
    print(f"Wrote deterministic entry scaffolds under {output_dir}")
    print(f"Root envelope ID: {envelope}")


if __name__ == "__main__":
    main()
